### ISSUE TITLE
How to page using the SDK

### ISSUE THREAD

**Issue by Hyperblaster** [XeroAPI/xero-node-sample-app#4]
I can't seem to figure out how to page the results

```
    let xero = new XeroClient(config, credentials);

    //////////////////////////////////////////////////////

    //Get all received payments
    return xero.payments.get({
             page:2,
            // 'If-Modified-Since': '2018-05-04T20:35:28'
        }).then(loaded, failed);
```

Still seems to return the same results, but if using the straight http url, appending page=2 should give me a second page?

https://developer.xero.com/documentation/api/requests-and-responses#get-modified

Am i missing something

**Comment by stunt-pilot** [comment]
You probably worked this out already @Hyperblaster, but the 'If-Modified-Since' date format has to be converted to a UTC date string to work. I'm having problems myself with paging the journals record:

`return self.currentApp.journals.get( { offset: transactionOffset }, { 'If-Modified-Since': after.toUTCString() } )`

This seems to ignore the 'If-Modified-Since' parameter.

**Comment by stunt-pilot** [comment]
I've added a feature request for more examples in the docs here.. 

[https://github.com/XeroAPI/xero-node/issues/269](url)

**Comment by SidneyAllen** [comment]
This code base is deprecated as it's for OAuth 1.0a.  

Please see the [OAuth 2.0 kitchen sync app](https://github.com/XeroAPI/xero-node-oauth2-app) for use with xero-node 4.x

OAuth1.0a deprecation schedule
* Early December 2019 - No new OAuth 1.0a apps created.
* Mid December 2019 - OAuth 2.0 migration endpoint available to partner apps.
* December 2020 - OAuth 1.0a no longer supported for existing integrations.
